# Generated by Django 3.2.9 on 2022-05-09 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0004_auto_20220508_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='time_posted',
            new_name='time',
        ),
    ]
