# Generated by Django 3.2.9 on 2022-05-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0005_rename_time_posted_profile_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='instructions',
            field=models.CharField(default='FILL THIS OUT', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
