# Generated by Django 3.2.9 on 2022-05-13 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstone', '0006_auto_20220513_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='game',
            name='likes',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
